### ISSUE TITLE
Simple example

### ISSUE THREAD

**Issue by Professr** [ryanplusplus/tiny#1]
This looks delightful and optimized, but there are no usage examples.  I can probably guess how to use it if I experiment enough, but a simple example would go a long way toward making this user friendly.  Could you mock up something that shows how to use the message bus?  That seems like it would cover a lot of the library's features.

**Comment by ryanplusplus** [comment]
Hey @Professr somehow I didn't manage to see this until now. Sorry for being 2 years late! This has mostly been for my own amusement, but I recently found out people have been using this. I'll take some time soon to provide belated documentation.
